### PR TITLE
Wip attach

### PR DESCRIPTION
**Pull request by svyotov**

### CODE REVIEW

**Comment by svyotov** [comment]
@Newman-Hui I do not feel this PR will be accepted by the maintainers of AstroMatt/atlassian-python-api.

**Comment by Newman-Hui** [comment]
@svyotov is it not possible to merge into our branch fork only?

**Comment by svyotov** [comment]
It is possible, but it would not be maintainable. We would not be able to take any new features the `AstroMatt` is developing etc. If we cannot write this code as something useful for the library then IMHO the best solution is to put it in the other repo, and use it from there. In the other repository you can still access the `_session` from the `confluence` object. That is not a good solution either but for me is better than having our own `atlassian-python-api` repository to maintain for those two functions.

**Comment by Newman-Hui** [comment]
He sent me this PR when i mentioned what i did 
https://github.com/AstroMatt/atlassian-python-api/pull/65/files

**Comment by svyotov** [comment]
@Newman-Hui this PR is to be closed (no longer needed)?

**Comment by Newman-Hui** [comment]
@svyotov correct, they (AstroMatt) made a commit addressing the bug i was running into, this is no longer needed

**Pull request closed without merging**
